import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import LandingSection from './LandingSection'
import VideoSection from './VideoSection'
import BannerSection from './BannerSection'
import PartnersSection from './PartnersSection'
import { createClient } from 'contentful'

export async function getStaticProps(){
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID!,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN!
  });

  const res = await client.getEntries({
    content_type: 'partner'
  })

  const resV = await client.getEntries({
    content_type: 'video'
  })

  client.getEntries()
  .then((response) => console.log(response.items))
  .catch(console.error)

  return {
    props: {
      partners: res.items,
      videos: resV.items
    }
  }
}

const inter = Inter({ subsets: ['latin'] })

export default function Home({ partners, videos }: { partners: Array<Object>, videos: Array<Object>}) {
  console.log("Partners", partners);
  console.log("Videos", videos);
  return (
    <>
      <Head>
        <title>GYTWorkz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gyt_logo_icon_PZt_icon.ico" />
      </Head>
      {/* <main> */}
        <LandingSection />
        <VideoSection videos={videos}/>
        <BannerSection/>
        <PartnersSection partners={partners}/>
      {/* </main> */}
    </>
  )
}
